### ISSUE TITLE
Warnings on ROS Melodic

### ISSUE THREAD

**Issue by dmcconachie** [UM-ARM-Lab/kuka_iiwa_interface#105]
To be addressed at some point:

`[ros.moveit_ros_planning.kinematics_plugin_loader]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/robot_description_kinematics/right_arm/kinematics_solver_attempts' from your configuration.
[ros.moveit_core.kinematics_base]: IK plugin for group 'right_arm' relies on deprecated API. Please implement initialize(RobotModel, ...).
[ros.moveit_core.kinematics_base]: IK plugin for group 'left_arm' relies on deprecated API. Please implement initialize(RobotModel, ...).
`

**Comment by PeterMitrano** [comment]
Fixed by 561389b63414cc1f09d11828ccf569eb66e1cc4f
