### ISSUE TITLE
Joint state publisher doesn't publish velocity.

### ISSUE THREAD

**Issue by mvandermerwe** [UM-ARM-Lab/kuka_iiwa_interface#135]
In `victor_hardware_interface/scripts/joint_state_publisher.py` gets set to empty list and never changed?

**Comment by mvandermerwe** [comment]
Controller doesn't send velocity.

**Comment by bsaund** [comment]
It might be possible to get and send velocity from the Kuka java Sunrise API.
Check the sunrise documentation (on `big_narstie`)

**Comment by mvandermerwe** [comment]
It's not urgent - Peter and I weren't sure if it was because it wasn't implemented or because of the switch to the MMint robots.
