### ISSUE TITLE
Test out iiwa_ros2 for victor

### ISSUE THREAD

**Issue by PeterMitrano** [UM-ARM-Lab/kuka_iiwa_interface#149]
https://github.com/ICube-Robotics/iiwa_ros2
Steps:

 - [x] Try out the iiwa_ros2 repo instructions
     - [x] Get one arm working without the gripper
- [x] start by forking the iiwa_ros2 repo into the armlab org
- [x] make an updated URDF with both arms. Probably start with the new urdf because theirs is very pretty, and just reference our victor.urdf to make a new victor.urdf. For now we can ignore the gripper in the urdf.
- [x] In `IiwaFRIHardwareInterface`, create _two_ `robotClient_` objects, one for left and one for right, and update the code to handle that. We can just assume a fixed ordering (left then right) in the vectors.
- [x] include all 14 joints (this will require renaming them!) [here](https://github.com/ICube-Robotics/iiwa_ros2/blob/main/iiwa_description/ros2_control/iiwa.r2c_hardware.xacro) and [here](https://github.com/ICube-Robotics/iiwa_ros2/blob/main/iiwa_description/config/iiwa_controllers.yaml)
- [ ] Upgrade arm_robots package files to ros2
- [ ] Get the victor basic demo script to run

For the robotiq 3f grippers
- [ ] Get a cable that can connect from the X651 port on the kuka to `kukacontrol` (ethernet? or usb?)
- [ ] Make a working ros2 driver for the robotiq 3 by combining [ros2_robotiq_gripper](https://github.com/PickNikRobotics/ros2_robotiq_gripper) and [robotiq_3f_gripper_control](https://github.com/ros-industrial/robotiq/tree/kinetic-devel/robotiq_3f_gripper_control)
- [ ] add the robotiq grippers in the URDF

**Comment by PeterMitrano** [comment]
So it turns out that using the gripper is actually the tricky part here. Using the iiwa_ros2 java file is really simple, I got it working in the sense that the FRI interface is started and waiting for commands. So some next steps are:

- [ ] Finish setting up the C++ FRI ROS2 side of things on the kukacontrol machine
- [ ] Calibrate the gripper since the arm still needs to know the mass of the robotiq gripper even though it's not going to be controlling it directly anymore
- [ ] Get the robotiq working. This means getting some code on the kukacontrol machine that works and making/using the right cables to connect the X651 port to the kuka control machine + power

**Comment by PeterMitrano** [comment]
I think a next step is to try to modify the controller to control both arms. Some steps (probably there are more)

- [ ] start by forking the iiwa_ros2 repo into the armlab org
- [ ] make an updated URDF with both arms. Probably start with the new urdf because theirs is very pretty, and just reference our victor.urdf to make a new victor.urdf. For now we can ignore the gripper in the urdf.
- [ ] include all 14 joints (this will require renaming them!) [here](https://github.com/ICube-Robotics/iiwa_ros2/blob/main/iiwa_description/ros2_control/iiwa.r2c_hardware.xacro) and [here](https://github.com/ICube-Robotics/iiwa_ros2/blob/main/iiwa_description/config/iiwa_controllers.yaml)
- [ ] In `IiwaFRIHardwareInterface`, create _two_ `robotClient_` objects, one for left and one for right, and update the code to handle that. We can just assume a fixed ordering (left then right) in the vectors.

**Comment by bsaund** [comment]
> However, the bad news is joint2 on the left arm is now making a crunchy bad noise.

FYI this happened before and we sent the robot back to Kuka for servicing. We had a loaner white kuka iiwa for awhile. I don't remember which arm

**Comment by PeterMitrano** [comment]
abandoning this in favor of just upgrading the stack in-place
