### ISSUE TITLE
Add Kinect to URDF

### ISSUE THREAD

**Issue by dmcconachie** [UM-ARM-Lab/kuka_iiwa_interface#58]
Right now there is nothing that prevents the OpenRAVE from planning motions through this space other than the fact that we are not performing any manipulation that is likely to move in this area. We should add a sensor there to help address this.

**Comment by PeterMitrano** [comment]
people move the camera(s) all the time, it doesn't make sense to put this in the URDF. For anyone coming across this, I would recommend using the moveit (python) API to publish an attached collision object box (fixed, or based on camera TF possible). Alternatively if you're using gazebo and the gazebo moveit planning scene plugin you can just put the camera in gazebo
